# Generated by Django 5.2.3 on 2025-06-20 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='sport_type',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
