# Generated by Django 5.2.3 on 2025-06-20 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_place_sport_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='sport_type',
            field=models.TextField(blank=True, default=''),
        ),
    ]
