# Generated by Django 5.2.3 on 2025-06-25 02:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_reservation_qr_image_reservation_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='_id_document',
            field=models.TextField(db_column='id_document', default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
