# Generated by Django 4.2.23 on 2025-08-04 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_userprofile__id_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='image_url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
